[[main]]
name = "Home"
url = ""
weight = -110

[[main]]
name = "Archive"
url = "archives/"
weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
name = "List"
identifier = "List"
weight = -108
[[main]]
parent = "List"
name = "Topics"
url = "topics/"
[[main]]
parent = "List"
name = "Tags"
url = "tags/"
[[main]]
parent = "List"
name = "Series"
url = "series/"

[[main]]
name = "About"
url = "about/"
weight = -107

# social menu links

[[social]]
name = "github"
type = "social"
weight = 1
url = "https://github.com/manojnakp"
#[[social]]
#name = "twitter"
#weight = 2
#url = "https://twitter.com/#"
[[social]]
name = "linkedin"
weight = 3
url = "https://in.linkedin.com/in/manojna-k-p-aa1857254"
[[social]]
name = "stackoverflow"
weight = 4
url = "https://stackoverflow.com/users/21192474/manojna"
[[social]]
name = "rss"
weight = 5
url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
